"""
Schemas and core abstractions for CLARITY.

CLARITY models clinical intake as a sequential decision process under uncertainty.
The central construct is the Clinical Risk Surface (CRS), which maps a structured
patient state to a probability of critical omission or escalation need.
"""

from typing import List, Optional
from pydantic import BaseModel, Field


class PatientState(BaseModel):
    """
    Structured representation of the patient state at a given time step.
    """
    presenting_complaint: str
    history_of_present_illness: Optional[str] = None
    medications: List[str] = Field(default_factory=list)
    allergies: List[str] = Field(default_factory=list)
    vitals: Optional[str] = None
    age: Optional[int] = None
    sex: Optional[str] = None


class RiskEstimate(BaseModel):
    """
    Output of the Clinical Risk Surface.
    """
    risk_score: float = Field(
        ge=0.0, le=1.0,
        description="Estimated probability of critical omission or need for escalation"
    )
    rationale: str
    red_flags: List[str] = Field(default_factory=list)
    escalate: bool


class SOAPNote(BaseModel):
    """
    Structured SOAP note generated by the system.
    """
    subjective: str
    objective: str
    assessment: str
    plan: str
